export interface LoginData {
    username: string;
    password: string;
}

export type SelectType = { label: string; value: string | number };

export interface PropertyMaster {
    propertyId?: number;
    ownerId?: number;
    householdNo?: string | null; 
    zone?: string | number | null;
    ward?: string | number | null;
    wardName?: string | null;
    propertyType?: string | null;
    typeOfOwnership?: string | number | null;
    otherTypeOfOwnerShip?: string | null;
    widthOfRoad?: string | null;
    areaOfPlot?: string | null;
    noOfFloors?: number;
    floorWiseDataId?: number;
    buildingNo?: string | null;
    flatNo?: string | null;
    flatSize?: string | null;
    elctricityCustomerId?: string | null;
    electricityAccountNo?: string | null;
    electricityBookNo?: string | null;
    electricityCategory?: string | null;
    buildingPlanApprovalNo?: string | null;
    buildingPlanApprovalDate?: string | null; 
    waterConsumerNo?: string | null;
    waterConnectionDate?: string | null; 
    district?: string | null;
    tahasil?: string | null;
    villageName?: string | null;
    khataNo?: string | null;
    plotNo?: string | null;
    propertyAddress?: string | null;
    propertyAddressDistrict?: string | null;
    propertyAddressCity?: string | null;
    propertyAddressPin?: string | null;
    latitude?: string | null;
    longitude?: string | null;
    isOwnerAddressSame?: boolean;
    ownerAddress?: string | null;
    ownerAddressDistrict?: string | null;
    ownerAddressCity?: string | null;
    ownerAddressPin?: string | null;
    plotArea?: string | null;
    dateOfAcquisition?: string | null; 
    useAsPerMasterPlan?: string | null;
    mobileTowerArea?: string | null;
    mobileTowerDateOfInstallation?: string | null; 
    hoardingArea?: string | null;
    hoardingDateOfInstallation?: string | null;
    petrolpumpUndergroundArea?: string | null;
    petrolpumpDateOfCompletion?: string | null;
    hasWaterHarvestingProvision?: boolean;
    attribute0?: string | null;
    attribute1?: string | null;
    attribute2?: string | null;
    attribute3?: string | null;
    attribute4?: string | null;
    attribute5?: string | null;
    attribute6?: string | null;
    attribute7?: string | null;
    attribute8?: string | null;
    attribute9?: string | null;
    mohallaName?: string | null | null;
    ownerName?: string | null;
    amount?: number;
    category?: string | number | null;
    subcategory?: string | number | null;
    rate?: number;
    createdBy?: string | null;
    createdOn?: string | null;
    updatedBy?: string | null;
    updatedOn?: string | null;
    status?: boolean;
    salutaion?: string | null;
    careOf?: string | null;
    guardianName?: string | null;
    gender?: string | null;
    dob?: string | null;
    mobile?: string | null;
    email?: string | null;
    pan?: string | null;
    aadhar?: string | null;
    isSpecialOwner?: boolean;
    identityProof?: string | null;
    photo?: string | null;
    specialCertificate?: string | null;
}